### ISSUE TITLE
404 on 'compiled.scss.css'

### ISSUE THREAD

**Issue by jmd-wilsons** [hayes0724/shopify-webpack-themekit#2]
I've followed adding {{ 'compiled.scss.css' | asset_url | stylesheet_tag }} to the theme.liquid file but when I run Webpack only the compiled.js is created which results in a 404 on compiled.scss.css. I've noticed the css/scss is staying within the compiled.js file instead of creating a separate compiled.scss.css file.

Any help would be appreciated.

Thanks.

**Comment by hayes0724** [comment]
For development mode it adds css to js. In production mode (using `npm run build`) it will create compiled.css

This has been fixed in 2e073f80936002e23de24a267d4a69f24b4c99b5
