### ISSUE TITLE
Preferred way of pushing to production?

### ISSUE THREAD

**Issue by treytt** [hayes0724/shopify-webpack-themekit#8]
Hey there I was looking through the code and documentation but couldn't find the best / easiest way to push my production code to Shopify? 

`npm start build` then zip & manual upload? I saw the deploy command was an empty file.

_Coming from Slate, thank you for putting this together!_

**Comment by DanPete** [comment]
I have been just doing `yarn build` command and then still having a config.yml, so I can set the directory as the dist folder and just use themekit's `theme deploy`

So kind of using two tools, but it works so far.

**Comment by treytt** [comment]
Thanks @DanPete, I didn't even think about using the existing themekit tools.
